"""
Brandix ISPS - Executive Summary Page
LLM-generated professional executive summaries by year
"""

import streamlit as st
import json
from pathlib import Path

st.set_page_config(page_title="Executive Summary", page_icon="📋", layout="wide")

# Custom CSS
st.markdown("""
    <style>
    .main {background-color: #f5f7fa;}
    .summary-section {
        background-color: white;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        margin: 15px 0;
    }
    h1 {color: #1f4788; font-weight: 600;}
    h2 {color: #2c5aa0;}
    h3 {color: #34495e;}
    </style>
""", unsafe_allow_html=True)

# Configuration
AVAILABLE_YEARS = ["2026", "2027", "2028", "2029", "2030"]
OUTPUTS_BASE = Path("outputs")

# Initialize session state
if 'selected_year' not in st.session_state:
    st.session_state.selected_year = "2026"

# Header
st.title("📋 Executive Summary")
st.markdown("### AI-Generated Strategic Insights")
st.markdown("---")

# Year Selection
col1, col2 = st.columns([1, 3])

with col1:
    selected_year = st.selectbox(
        "Select Year",
        AVAILABLE_YEARS,
        index=AVAILABLE_YEARS.index(st.session_state.selected_year),
        key='exec_year_selector'
    )
    
    if selected_year != st.session_state.selected_year:
        st.session_state.selected_year = selected_year
        st.rerun()

with col2:
    st.info(f"📅 Executive Summary for **Year {selected_year}**")

# Load Data
@st.cache_data
def load_executive_summary(year):
    """Load executive summary for a specific year"""
    summary_file = OUTPUTS_BASE / year / 'executive_summary.json'
    
    if not summary_file.exists():
        return None
    
    with open(summary_file, 'r', encoding='utf-8') as f:
        return json.load(f)

# Load summary
summary = load_executive_summary(selected_year)

if summary is None:
    st.error(f"⚠️ No executive summary found for year {selected_year}")
    st.info("👉 Go to **'⚙️ Run Analysis'** page to generate executive summary")
    st.stop()

st.success(f"✅ Executive summary available for {selected_year}")

st.markdown("---")

# Display Summary Sections
sections = [
    ("📊 Executive Overview", "overview"),
    ("🔍 Key Findings", "key_findings"),
    ("🔴 Critical Gaps", "critical_gaps"),
    ("💡 Strategic Recommendations", "recommendations"),
    ("⚠️ Risk Assessment", "risk_assessment"),
    ("🎯 Next Steps", "next_steps")
]

for title, key in sections:
    st.markdown(f"""
    <div class="summary-section">
    <h3>{title}</h3>
    </div>
    """, unsafe_allow_html=True)
    
    content = summary.get(key, "Not available")
    st.markdown(content)
    st.markdown("---")

# Download Section
st.subheader("📥 Download Executive Summary")

col1, col2 = st.columns(2)

with col1:
    # JSON download
    json_data = json.dumps(summary, indent=2)
    st.download_button(
        label="📄 Download as JSON",
        data=json_data,
        file_name=f"executive_summary_{selected_year}.json",
        mime="application/json",
        use_container_width=True
    )

with col2:
    # Markdown download
    md_file = OUTPUTS_BASE / selected_year / "executive_summary.md"
    if md_file.exists():
        with open(md_file, 'r', encoding='utf-8') as f:
            md_data = f.read()
        
        st.download_button(
            label="📋 Download as Markdown",
            data=md_data,
            file_name=f"executive_summary_{selected_year}.md",
            mime="text/markdown",
            use_container_width=True
        )

# Navigation
st.markdown("---")

col1, col2 = st.columns(2)

with col1:
    if st.button("📊 View Detailed Results", use_container_width=True):
        st.switch_page("pages/03_View_Results.py")

with col2:
    if st.button("📈 Compare Years", use_container_width=True):
        st.switch_page("pages/05_Multi_Year_Comparison.py")

st.markdown("---")
st.caption("🤖 **Generated by:** Phi-3 Mini via Ollama | **Technology:** Local LLM with RAG Pipeline")